title: WHAT THE FONT
description: ""
footer_text: Copyright 2021 Hetanshi Joshi
header_feature_image: ../uploads/white-name-youtube-channel-art-.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 40vmax
navbarheight: 55px
logo: ../uploads/f.png
favicon: ../uploads/f.png
gridlayout: false
fixednavbar: false
upzoom: true
