title: WHAT THE FONT
description: ""
footer_text: Copyright 2021 Hetanshi Joshi
header_feature_image: ../uploads/blog-1-f-img.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 40vmax
navbarheight: 55px
logo: ../uploads/f.png
favicon: ../uploads/android-chrome-192x192.png
gridlayout: false
fixednavbar: true
upzoom: true
