title: Rekha Graphy
description: ""
footer_text: Copyright 2021 Hetanshi Joshi
header_feature_image: ../uploads/image-1-.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: ../uploads/rekhatype.png
gridlayout: false
fixednavbar: false
upzoom: true
