title: hetanshijoshi
description: ""
footer_text: Copyright 2021 Hetanshi Joshi
header_feature_image: ../uploads/screenshot-2021-10-04-at-15.31.17.png
header_text: Hetanshi Joshi
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
