title: hetanshijoshi
description: ""
footer_text: Copyright 2021 Hetanshi Joshi
header_feature_image: ../uploads/placeholder2.jpg
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
