title: Rekha Graphy
description: ""
footer_text: Copyright 2021 Hetanshi Joshi
header_feature_image: ../uploads/blue-and-gold-india-wedding-announcement-instagram-post-2-.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 60vmax
navbarheight: 55px
logo: ../uploads/rg-1-.png
favicon: ../uploads/rg-1-.png
gridlayout: false
fixednavbar: false
upzoom: true
